export const DEFAULT_BUDGET_GROUPS = [
  { name: "Needs", percentage: 50, sortOrder: 0 },
  { name: "Savings", percentage: 20, sortOrder: 1 },
  { name: "Wants", percentage: 30, sortOrder: 2 },
] as const;

export const DEFAULT_CATEGORY_MAPPING: Record<string, string> = {
  // Needs — essential, unavoidable expenses
  "Rent": "Needs",
  "Mortgage": "Needs",
  "Property Taxes": "Needs",
  "Home Insurance": "Needs",
  "HOA Fees": "Needs",
  "Maintenance and Repairs": "Needs",
  "Electric": "Needs",
  "Gas": "Needs",
  "Water": "Needs",
  "Trash": "Needs",
  "Internet": "Needs",
  "Phone": "Needs",
  "Cable": "Needs",
  "Telecommunication": "Needs",
  "Groceries": "Needs",
  "Healthcare": "Needs",
  "Doctor": "Needs",
  "Dentist": "Needs",
  "Pharmacy": "Needs",
  "Vision Care": "Needs",
  "Medical Supplies": "Needs",
  "Veterinarian": "Needs",
  "Health Insurance": "Needs",
  "Life Insurance": "Needs",
  "Disability Insurance": "Needs",
  "Car Insurance": "Needs",
  "Gas Stations": "Needs",
  "Public Transportation": "Needs",
  "Parking": "Needs",
  "Taxis": "Needs",
  "Ride Share": "Needs",
  "Tolls": "Needs",
  "Tolls and Fees": "Needs",
  "Auto Payment": "Needs",
  "Car Repairs": "Needs",
  "Loan": "Needs",
  "Loan Payments": "Needs",
  "Student Loan": "Needs",
  "Personal Loan": "Needs",
  "Auto Loan": "Needs",
  "Credit Card": "Needs",
  "Minimum Payment": "Needs",
  "Vehicle Maintenance": "Needs",
  "Tuition": "Needs",
  "Childcare": "Needs",
  "Day Care": "Needs",
  "Babysitter": "Needs",
  "Alimony": "Needs",
  "Child Support": "Needs",
  "Legal": "Needs",
  "Accounting": "Needs",
  "Tax Preparation": "Needs",
  "Taxes": "Needs",
  "Federal Tax": "Needs",
  "State Tax": "Needs",
  "Local Tax": "Needs",
  "Bank Fees": "Needs",
  "Overdraft": "Needs",
  "ATM Fees": "Needs",
  "Late Payment": "Needs",
  "Interest Charged": "Needs",
  "Identity Theft Protection": "Needs",
  "Dry Cleaning": "Needs",
  "Laundry": "Needs",

  // Savings — future-oriented, investments, debt reduction above minimums
  "Savings": "Savings",
  "Transfer": "Savings",
  "Deposit": "Savings",
  "Investment": "Savings",
  "Buy": "Savings",
  "Sell": "Savings",
  "Trade": "Savings",
  "Retirement": "Savings",
  "IRA": "Savings",
  "401k": "Savings",
  "401a": "Savings",
  "403b": "Savings",
  "457b": "Savings",
  "Pension": "Savings",
  "Annuity": "Savings",
  "Brokerage": "Savings",
  "Mutual Fund": "Savings",
  "Index Fund": "Savings",
  "ETF": "Savings",
  "Stock": "Savings",
  "Bond": "Savings",
  "CD": "Savings",
  "Certificate of Deposit": "Savings",
  "Treasury": "Savings",
  "Money Market": "Savings",
  "Dividend": "Savings",
  "Capital Gains": "Savings",
  "Interest Earned": "Savings",
  "Interest Income": "Savings",
  "Financial Planning": "Savings",
  "Wealth Management": "Savings",
  "Cryptocurrency": "Savings",
  "Cash Management": "Savings",
  "HSA": "Savings",
  "FSA": "Savings",
  "Education Savings": "Savings",
  "529 Plan": "Savings",
  "Coverdell ESA": "Savings",
  "Emergency Fund": "Savings",
  "Home Improvement": "Savings",

  // Wants — discretionary, lifestyle
  "Restaurants": "Wants",
  "Fast Food": "Wants",
  "Coffee Shop": "Wants",
  "Bar": "Wants",
  "Brewery": "Wants",
  "Winery": "Wants",
  "Alcohol": "Wants",
  "Tobacco": "Wants",
  "Cannabis": "Wants",
  "Entertainment": "Wants",
  "Movies": "Wants",
  "Theatre": "Wants",
  "Concerts": "Wants",
  "Music": "Wants",
  "Streaming": "Wants",
  "Games": "Wants",
  "Video Games": "Wants",
  "Arcade": "Wants",
  "Amusement": "Wants",
  "Museums": "Wants",
  "Zoo": "Wants",
  "Aquarium": "Wants",
  "Parks": "Wants",
  "Recreation": "Wants",
  "Hobbies": "Wants",
  "Arts and Crafts": "Wants",
  "Collectibles": "Wants",
  "Shopping": "Wants",
  "Clothing": "Wants",
  "Shoes": "Wants",
  "Accessories": "Wants",
  "Jewelry": "Wants",
  "Watches": "Wants",
  "Electronics": "Wants",
  "Computers": "Wants",
  "Software": "Wants",
  "Apps": "Wants",
  "Books": "Wants",
  "Magazines": "Wants",
  "Newspapers": "Wants",
  "Digital Media": "Wants",
  "Furniture": "Wants",
  "Home Decor": "Wants",
  "Kitchen": "Wants",
  "Garden": "Wants",
  "Hardware": "Wants",
  "Sporting Goods": "Wants",
  "Sporting Equipment": "Wants",
  "Bicycles": "Wants",
  "Camping": "Wants",
  "Fishing": "Wants",
  "Hunting": "Wants",
  "Golf": "Wants",
  "Skiing": "Wants",
  "Snowboarding": "Wants",
  "Surfing": "Wants",
  "Travel": "Wants",
  "Hotels": "Wants",
  "Motels": "Wants",
  "Lodging": "Wants",
  "Airlines": "Wants",
  "Air Travel": "Wants",
  "Car Rental": "Wants",
  "Cruises": "Wants",
  "Vacation": "Wants",
  "Resort": "Wants",
  "Fitness": "Wants",
  "Gym": "Wants",
  "Yoga": "Wants",
  "Pilates": "Wants",
  "Personal Training": "Wants",
  "Salon": "Wants",
  "Barber": "Wants",
  "Spa": "Wants",
  "Massage": "Wants",
  "Nails": "Wants",
  "Hair": "Wants",
  "Cosmetics": "Wants",
  "Beauty": "Wants",
  "Skincare": "Wants",
  "Perfume": "Wants",
  "Gifts": "Wants",
  "Donations": "Wants",
  "Charity": "Wants",
  "Nonprofit": "Wants",
  "Religious": "Wants",
  "Political": "Wants",
  "Subscriptions": "Wants",
  "Memberships": "Wants",
  "Clubs": "Wants",
  "Pets": "Wants",
  "Pet Food": "Wants",
  "Pet Supplies": "Wants",
  "Pet Grooming": "Wants",
  "Pet Insurance": "Wants",
  "Vending Machine": "Wants",
  "Convenience Store": "Wants",
  "Lottery": "Wants",
  "Casino": "Wants",
  "Gambling": "Wants",
  "Catering": "Wants",
  "Event Planning": "Wants",
  "Party Supplies": "Wants",
  "Photography": "Wants",
  "Photo Printing": "Wants",
  "Flowers": "Wants",
  "Dating": "Wants",
  "Escort": "Wants",
};
