export const DEFAULT_BUDGET_GROUPS = [
  { name: "Needs", percentage: 50, sortOrder: 0 },
  { name: "Savings", percentage: 20, sortOrder: 1 },
  { name: "Wants", percentage: 30, sortOrder: 2 },
] as const;

export interface DefaultCategoryMapping {
  budgetCategory: string;
  group: "Needs" | "Savings" | "Wants";
}

export const DEFAULT_CATEGORY_MAPPING: Record<string, DefaultCategoryMapping> = {
  // ---- Needs: essential, unavoidable ----
  "Rent": { budgetCategory: "Rent", group: "Needs" },
  "Mortgage": { budgetCategory: "Mortgage", group: "Needs" },
  "Loans and Mortgages": { budgetCategory: "Mortgage", group: "Needs" },
  "Property Taxes": { budgetCategory: "Property Taxes", group: "Needs" },
  "Home Insurance": { budgetCategory: "Insurance", group: "Needs" },
  "HOA Fees": { budgetCategory: "HOA Fees", group: "Needs" },
  "Maintenance and Repairs": { budgetCategory: "Home Maintenance", group: "Needs" },
  "Pest Control": { budgetCategory: "Home Maintenance", group: "Needs" },
  "Electric": { budgetCategory: "Electric", group: "Needs" },
  "Gas": { budgetCategory: "Gas", group: "Needs" },
  "Water": { budgetCategory: "Water", group: "Needs" },
  "Trash": { budgetCategory: "Trash", group: "Needs" },
  "Sanitary and Waste Management": { budgetCategory: "Trash", group: "Needs" },
  "Internet": { budgetCategory: "Internet", group: "Needs" },
  "Cable": { budgetCategory: "Internet", group: "Needs" },
  "Phone": { budgetCategory: "Phone", group: "Needs" },
  "Telecommunication": { budgetCategory: "Phone", group: "Needs" },
  "Groceries": { budgetCategory: "Groceries", group: "Needs" },
  "Supermarkets and Groceries": { budgetCategory: "Groceries", group: "Needs" },
  "Convenience Store": { budgetCategory: "Groceries", group: "Needs" },
  "Convenience Stores": { budgetCategory: "Groceries", group: "Needs" },
  "Warehouses and Wholesale Stores": { budgetCategory: "Groceries", group: "Needs" },
  "Healthcare": { budgetCategory: "Healthcare", group: "Needs" },
  "Healthcare Services": { budgetCategory: "Healthcare", group: "Needs" },
  "Doctor": { budgetCategory: "Healthcare", group: "Needs" },
  "Dentist": { budgetCategory: "Healthcare", group: "Needs" },
  "Pharmacy": { budgetCategory: "Healthcare", group: "Needs" },
  "Vision Care": { budgetCategory: "Healthcare", group: "Needs" },
  "Medical Supplies": { budgetCategory: "Healthcare", group: "Needs" },
  "Veterinarian": { budgetCategory: "Vet", group: "Needs" },
  "Pets": { budgetCategory: "Vet", group: "Needs" },
  "Pet Food": { budgetCategory: "Pets", group: "Needs" },
  "Pet Supplies": { budgetCategory: "Pets", group: "Needs" },
  "Pet Grooming": { budgetCategory: "Pets", group: "Needs" },
  "Pet Insurance": { budgetCategory: "Pets", group: "Needs" },
  "Health Insurance": { budgetCategory: "Insurance", group: "Needs" },
  "Life Insurance": { budgetCategory: "Insurance", group: "Needs" },
  "Disability Insurance": { budgetCategory: "Insurance", group: "Needs" },
  "Car Insurance": { budgetCategory: "Insurance", group: "Needs" },
  "Insurance": { budgetCategory: "Insurance", group: "Needs" },
  "Identity Theft Protection": { budgetCategory: "Insurance", group: "Needs" },
  "Gas Stations": { budgetCategory: "Gas", group: "Needs" },
  "Public Transportation": { budgetCategory: "Transportation", group: "Needs" },
  "Parking": { budgetCategory: "Parking", group: "Needs" },
  "Taxis": { budgetCategory: "Transportation", group: "Needs" },
  "Ride Share": { budgetCategory: "Transportation", group: "Needs" },
  "Tolls": { budgetCategory: "Tolls", group: "Needs" },
  "Tolls and Fees": { budgetCategory: "Tolls", group: "Needs" },
  "Auto Payment": { budgetCategory: "Car Payments", group: "Needs" },
  "Car Dealers and Leasing": { budgetCategory: "Car Payments", group: "Needs" },
  "Car Repairs": { budgetCategory: "Car Maintenance", group: "Needs" },
  "Vehicle Maintenance": { budgetCategory: "Car Maintenance", group: "Needs" },
  "Car Parts and Accessories": { budgetCategory: "Car Maintenance", group: "Needs" },
  "Maintenance and Repair": { budgetCategory: "Car Maintenance", group: "Needs" },
  "Automotive": { budgetCategory: "Car Maintenance", group: "Needs" },
  "Loan": { budgetCategory: "Loan", group: "Needs" },
  "Loan Payments": { budgetCategory: "Loan", group: "Needs" },
  "Student Loan": { budgetCategory: "Loan", group: "Needs" },
  "Personal Loan": { budgetCategory: "Loan", group: "Needs" },
  "Auto Loan": { budgetCategory: "Car Payments", group: "Needs" },
  "Credit Card": { budgetCategory: "Credit Card Payments", group: "Needs" },
  "Minimum Payment": { budgetCategory: "Credit Card Payments", group: "Needs" },
  "Tuition": { budgetCategory: "Education", group: "Needs" },
  "Childcare": { budgetCategory: "Childcare", group: "Needs" },
  "Day Care": { budgetCategory: "Childcare", group: "Needs" },
  "Babysitter": { budgetCategory: "Childcare", group: "Needs" },
  "Alimony": { budgetCategory: "Alimony", group: "Needs" },
  "Child Support": { budgetCategory: "Child Support", group: "Needs" },
  "Legal": { budgetCategory: "Legal", group: "Needs" },
  "Accounting": { budgetCategory: "Legal", group: "Needs" },
  "Tax Preparation": { budgetCategory: "Taxes", group: "Needs" },
  "Taxes": { budgetCategory: "Taxes", group: "Needs" },
  "Federal Tax": { budgetCategory: "Taxes", group: "Needs" },
  "State Tax": { budgetCategory: "Taxes", group: "Needs" },
  "Local Tax": { budgetCategory: "Taxes", group: "Needs" },
  "Government Departments and Agencies": { budgetCategory: "Taxes", group: "Needs" },
  "Payment": { budgetCategory: "Taxes", group: "Needs" },
  "Bank Fees": { budgetCategory: "Bank Fees", group: "Needs" },
  "Overdraft": { budgetCategory: "Bank Fees", group: "Needs" },
  "ATM Fees": { budgetCategory: "Bank Fees", group: "Needs" },
  "ATM": { budgetCategory: "Bank Fees", group: "Needs" },
  "Late Payment": { budgetCategory: "Bank Fees", group: "Needs" },
  "Interest Charged": { budgetCategory: "Interest Charged", group: "Needs" },
  "Dry Cleaning": { budgetCategory: "Cleaning", group: "Needs" },
  "Laundry": { budgetCategory: "Cleaning", group: "Needs" },

  // ---- Savings: future-oriented, investments, debt reduction above minimums ----
  "Savings": { budgetCategory: "Savings", group: "Savings" },
  "Saving Transfers": { budgetCategory: "Savings", group: "Savings" },
  "Transfer": { budgetCategory: "Transfers", group: "Savings" },
  "Deposit": { budgetCategory: "Deposits", group: "Savings" },
  "Investment": { budgetCategory: "Investments", group: "Savings" },
  "Buy": { budgetCategory: "Investments", group: "Savings" },
  "Sell": { budgetCategory: "Investments", group: "Savings" },
  "Trade": { budgetCategory: "Investments", group: "Savings" },
  "Retirement": { budgetCategory: "Investments", group: "Savings" },
  "IRA": { budgetCategory: "Investments", group: "Savings" },
  "401k": { budgetCategory: "Investments", group: "Savings" },
  "401a": { budgetCategory: "Investments", group: "Savings" },
  "403b": { budgetCategory: "Investments", group: "Savings" },
  "457b": { budgetCategory: "Investments", group: "Savings" },
  "Pension": { budgetCategory: "Investments", group: "Savings" },
  "Annuity": { budgetCategory: "Investments", group: "Savings" },
  "Brokerage": { budgetCategory: "Investments", group: "Savings" },
  "Mutual Fund": { budgetCategory: "Investments", group: "Savings" },
  "Index Fund": { budgetCategory: "Investments", group: "Savings" },
  "ETF": { budgetCategory: "Investments", group: "Savings" },
  "Stock": { budgetCategory: "Investments", group: "Savings" },
  "Bond": { budgetCategory: "Investments", group: "Savings" },
  "CD": { budgetCategory: "Investments", group: "Savings" },
  "Certificate of Deposit": { budgetCategory: "Investments", group: "Savings" },
  "Treasury": { budgetCategory: "Investments", group: "Savings" },
  "Money Market": { budgetCategory: "Investments", group: "Savings" },
  "Cryptocurrency": { budgetCategory: "Investments", group: "Savings" },
  "Dividend": { budgetCategory: "Dividend Income", group: "Savings" },
  "Capital Gains": { budgetCategory: "Capital Gains", group: "Savings" },
  "Interest Earned": { budgetCategory: "Interest Earned", group: "Savings" },
  "Interest Income": { budgetCategory: "Interest Income", group: "Savings" },
  "Financial Planning": { budgetCategory: "Financial Planning", group: "Savings" },
  "Wealth Management": { budgetCategory: "Financial Planning", group: "Savings" },
  "Cash Management": { budgetCategory: "Cash Management", group: "Savings" },
  "HSA": { budgetCategory: "Health Savings", group: "Savings" },
  "FSA": { budgetCategory: "Health Savings", group: "Savings" },
  "Education Savings": { budgetCategory: "Education Savings", group: "Savings" },
  "529 Plan": { budgetCategory: "Education Savings", group: "Savings" },
  "Coverdell ESA": { budgetCategory: "Education Savings", group: "Savings" },
  "Emergency Fund": { budgetCategory: "Emergency Fund", group: "Savings" },
  "Home Improvement": { budgetCategory: "Home Improvement", group: "Savings" },

  // ---- Wants: discretionary, lifestyle ----
  "Restaurants": { budgetCategory: "Dining", group: "Wants" },
  "Fast Food": { budgetCategory: "Dining", group: "Wants" },
  "Catering": { budgetCategory: "Dining", group: "Wants" },
  "Coffee Shop": { budgetCategory: "Coffee", group: "Wants" },
  "Bar": { budgetCategory: "Alcohol", group: "Wants" },
  "Brewery": { budgetCategory: "Alcohol", group: "Wants" },
  "Winery": { budgetCategory: "Alcohol", group: "Wants" },
  "Alcohol": { budgetCategory: "Alcohol", group: "Wants" },
  "Tobacco": { budgetCategory: "Tobacco", group: "Wants" },
  "Cannabis": { budgetCategory: "Tobacco", group: "Wants" },
  "Entertainment": { budgetCategory: "Entertainment", group: "Wants" },
  "Arts and Entertainment": { budgetCategory: "Entertainment", group: "Wants" },
  "Food and Beverage Store": { budgetCategory: "Entertainment", group: "Wants" },
  "Movies": { budgetCategory: "Entertainment", group: "Wants" },
  "Theatre": { budgetCategory: "Entertainment", group: "Wants" },
  "Concerts": { budgetCategory: "Entertainment", group: "Wants" },
  "Music": { budgetCategory: "Entertainment", group: "Wants" },
  "Amusement": { budgetCategory: "Entertainment", group: "Wants" },
  "Museums": { budgetCategory: "Entertainment", group: "Wants" },
  "Zoo": { budgetCategory: "Entertainment", group: "Wants" },
  "Aquarium": { budgetCategory: "Entertainment", group: "Wants" },
  "Parks": { budgetCategory: "Entertainment", group: "Wants" },
  "Recreation": { budgetCategory: "Entertainment", group: "Wants" },
  "Event Planning": { budgetCategory: "Entertainment", group: "Wants" },
  "Party Supplies": { budgetCategory: "Entertainment", group: "Wants" },
  "Streaming": { budgetCategory: "Streaming", group: "Wants" },
  "Subscription": { budgetCategory: "Streaming", group: "Wants" },
  "Subscriptions": { budgetCategory: "Streaming", group: "Wants" },
  "Music, Video and DVD": { budgetCategory: "Streaming", group: "Wants" },
  "Games": { budgetCategory: "Gaming", group: "Wants" },
  "Video Games": { budgetCategory: "Gaming", group: "Wants" },
  "Arcade": { budgetCategory: "Gaming", group: "Wants" },
  "Hobbies": { budgetCategory: "Hobbies", group: "Wants" },
  "Arts and Crafts": { budgetCategory: "Hobbies", group: "Wants" },
  "Collectibles": { budgetCategory: "Hobbies", group: "Wants" },
  "Shopping": { budgetCategory: "Shopping", group: "Wants" },
  "Department Stores": { budgetCategory: "Shopping", group: "Wants" },
  "Discount Stores": { budgetCategory: "Shopping", group: "Wants" },
  "Shops": { budgetCategory: "Shopping", group: "Wants" },
  "Clothing": { budgetCategory: "Clothing", group: "Wants" },
  "Clothing and Accessories": { budgetCategory: "Clothing", group: "Wants" },
  "Shoes": { budgetCategory: "Clothing", group: "Wants" },
  "Accessories": { budgetCategory: "Clothing", group: "Wants" },
  "Jewelry": { budgetCategory: "Jewelry", group: "Wants" },
  "Watches": { budgetCategory: "Jewelry", group: "Wants" },
  "Electronics": { budgetCategory: "Electronics", group: "Wants" },
  "Computers": { budgetCategory: "Electronics", group: "Wants" },
  "Digital Purchase": { budgetCategory: "Online Shopping", group: "Wants" },
  "PayPal": { budgetCategory: "Online Shopping", group: "Wants" },
  "Software": { budgetCategory: "Software", group: "Wants" },
  "Software Development": { budgetCategory: "Software", group: "Wants" },
  "Service": { budgetCategory: "Software", group: "Wants" },
  "Apps": { budgetCategory: "Software", group: "Wants" },
  "Books": { budgetCategory: "Books", group: "Wants" },
  "Magazines": { budgetCategory: "Books", group: "Wants" },
  "Newspapers": { budgetCategory: "Books", group: "Wants" },
  "Digital Media": { budgetCategory: "Digital Media", group: "Wants" },
  "Furniture": { budgetCategory: "Home Goods", group: "Wants" },
  "Home Decor": { budgetCategory: "Home Goods", group: "Wants" },
  "Kitchen": { budgetCategory: "Home Goods", group: "Wants" },
  "Garden": { budgetCategory: "Home Goods", group: "Wants" },
  "Hardware": { budgetCategory: "Home Improvement", group: "Wants" },
  "Hardware Store": { budgetCategory: "Home Improvement", group: "Wants" },
  "Construction Supplies": { budgetCategory: "Home Improvement", group: "Wants" },
  "Sporting Goods": { budgetCategory: "Sporting Goods", group: "Wants" },
  "Sporting Equipment": { budgetCategory: "Sporting Goods", group: "Wants" },
  "Bicycles": { budgetCategory: "Sporting Goods", group: "Wants" },
  "Golf": { budgetCategory: "Sporting Goods", group: "Wants" },
  "Camping": { budgetCategory: "Outdoor Recreation", group: "Wants" },
  "Fishing": { budgetCategory: "Outdoor Recreation", group: "Wants" },
  "Hunting": { budgetCategory: "Outdoor Recreation", group: "Wants" },
  "Skiing": { budgetCategory: "Outdoor Recreation", group: "Wants" },
  "Snowboarding": { budgetCategory: "Outdoor Recreation", group: "Wants" },
  "Surfing": { budgetCategory: "Outdoor Recreation", group: "Wants" },
  "Floats": { budgetCategory: "Outdoor Recreation", group: "Wants" },
  "Travel": { budgetCategory: "Travel", group: "Wants" },
  "Hotels": { budgetCategory: "Travel", group: "Wants" },
  "Motels": { budgetCategory: "Travel", group: "Wants" },
  "Lodging": { budgetCategory: "Travel", group: "Wants" },
  "Airlines": { budgetCategory: "Travel", group: "Wants" },
  "Air Travel": { budgetCategory: "Travel", group: "Wants" },
  "Car Rental": { budgetCategory: "Travel", group: "Wants" },
  "Cruises": { budgetCategory: "Travel", group: "Wants" },
  "Vacation": { budgetCategory: "Travel", group: "Wants" },
  "Resort": { budgetCategory: "Travel", group: "Wants" },
  "Fitness": { budgetCategory: "Fitness", group: "Wants" },
  "Gym": { budgetCategory: "Fitness", group: "Wants" },
  "Gyms and Fitness Centers": { budgetCategory: "Fitness", group: "Wants" },
  "Yoga": { budgetCategory: "Fitness", group: "Wants" },
  "Pilates": { budgetCategory: "Fitness", group: "Wants" },
  "Personal Training": { budgetCategory: "Fitness", group: "Wants" },
  "Salon": { budgetCategory: "Personal Care", group: "Wants" },
  "Barber": { budgetCategory: "Personal Care", group: "Wants" },
  "Spa": { budgetCategory: "Personal Care", group: "Wants" },
  "Massage": { budgetCategory: "Personal Care", group: "Wants" },
  "Nails": { budgetCategory: "Personal Care", group: "Wants" },
  "Hair": { budgetCategory: "Personal Care", group: "Wants" },
  "Cosmetics": { budgetCategory: "Personal Care", group: "Wants" },
  "Beauty": { budgetCategory: "Personal Care", group: "Wants" },
  "Skincare": { budgetCategory: "Personal Care", group: "Wants" },
  "Perfume": { budgetCategory: "Personal Care", group: "Wants" },
  "Personal Care": { budgetCategory: "Personal Care", group: "Wants" },
  "Gifts": { budgetCategory: "Gifts", group: "Wants" },
  "Flowers": { budgetCategory: "Gifts", group: "Wants" },
  "Donations": { budgetCategory: "Donations", group: "Wants" },
  "Charity": { budgetCategory: "Donations", group: "Wants" },
  "Nonprofit": { budgetCategory: "Donations", group: "Wants" },
  "Religious": { budgetCategory: "Donations", group: "Wants" },
  "Political": { budgetCategory: "Donations", group: "Wants" },
  "Memberships": { budgetCategory: "Subscriptions", group: "Wants" },
  "Clubs": { budgetCategory: "Subscriptions", group: "Wants" },
  "Vending Machine": { budgetCategory: "Snacks", group: "Wants" },
  "Lottery": { budgetCategory: "Gambling", group: "Wants" },
  "Casino": { budgetCategory: "Gambling", group: "Wants" },
  "Gambling": { budgetCategory: "Gambling", group: "Wants" },
  "Photography": { budgetCategory: "Photography", group: "Wants" },
  "Photo Printing": { budgetCategory: "Photography", group: "Wants" },
  "Car Wash and Detail": { budgetCategory: "Car Care", group: "Wants" },
  "Shipping and Freight": { budgetCategory: "Shipping", group: "Wants" },
  "Dating": { budgetCategory: "Dating", group: "Wants" },
  "Escort": { budgetCategory: "Dating", group: "Wants" },
};
